# Generated by Django 5.1.4 on 2026-05-14 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='fuel_app.church')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('target_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='fuel_app.fuelstation')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('station', 'year', 'month')},
            },
        ),
    ]
