# Generated by Django 5.1.4 on 2026-06-05 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0002_disbursement_stationtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Form submission timestamp (Horodateur)', null=True, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('city_country', models.CharField(blank=True, max_length=120, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=60, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=40, null=True)),
                ('daily_fuel_consumption', models.CharField(blank=True, help_text='Litres per day (range)', max_length=30, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=30, null=True)),
                ('has_health_coverage', models.BooleanField(blank=True, null=True)),
                ('has_care_access_difficulty', models.BooleanField(blank=True, null=True)),
                ('dependents', models.CharField(blank=True, help_text='Number of dependents (range)', max_length=20, null=True)),
                ('field_agent', models.CharField(blank=True, max_length=120, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
