# Generated by Django 5.1.4 on 2026-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_app', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='driver_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized phone of the driver who paid this levy.', max_length=30, null=True),
        ),
    ]
