<script lang="ts">
  import { onMount } from "svelte";
  import { can } from "../lib/auth";
  import { churchesApi, disbursementsApi } from "../lib/api";
  import { dateOnly, dateTime, money } from "../lib/format";
  import EmptyState from "../lib/components/EmptyState.svelte";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import Loading from "../lib/components/Loading.svelte";
  import Modal from "../lib/components/Modal.svelte";
  import Pagination from "../lib/components/Pagination.svelte";
  import StatusBadge from "../lib/components/StatusBadge.svelte";

  let rows: any[] = []; let churches: any[] = []; let total = 0; let totals: { total: string | number; count: number } = { total: 0, count: 0 }; let page = 1; let statusFilter = ""; let loading = true; let error = ""; let modalOpen = false; let editing: any = null; let busy = false; let formError = "";
  let form: Record<string, any> = {};
  $: writable = can("manage_disbursements");
  function blank(): Record<string, any> { return { church: "", period_start: "", period_end: "", amount_usd: "", amount_cdf: "", status: "SCHEDULED", payment_method: "", notes: "" }; }
  async function load(): Promise<void> { loading = true; error = ""; try { const [response, churchResponse] = await Promise.all([disbursementsApi.list({ page, page_size: 50, status: statusFilter }), churchesApi.list({ page_size: 100 })]); rows = response.results; total = response.count; totals = response.totals; churches = churchResponse.results; } catch (err) { error = err instanceof Error ? err.message : "Unable to load disbursements."; } finally { loading = false; } }
  function openCreate(): void { editing = null; form = blank(); formError = ""; modalOpen = true; }
  function openEdit(row: any): void { editing = row; form = { ...blank(), ...row, amount_usd: row.amount_usd || "", amount_cdf: row.amount_cdf || "" }; formError = ""; modalOpen = true; }
  function close(): void { if (!busy) modalOpen = false; }
  async function save(): Promise<void> { busy = true; formError = ""; try { const body = { ...form, amount_usd: String(form.amount_usd), amount_cdf: String(form.amount_cdf || 0) }; editing ? await disbursementsApi.update(editing.id, body) : await disbursementsApi.create(body); modalOpen = false; await load(); } catch (err) { formError = err instanceof Error ? err.message : "Unable to save disbursement."; } finally { busy = false; } }
  async function pay(row: any): Promise<void> { if (!confirm(`Mark ${row.reference} as paid?`)) return; try { await disbursementsApi.pay(row.id); await load(); } catch (err) { error = err instanceof Error ? err.message : "Unable to mark payment."; } }
  onMount(load);
</script>

<div class="page-heading"><div><h2>Disbursements</h2><p>{totals.count} records · <span class="money">{money(totals.total)}</span> scheduled and paid</p></div>{#if writable}<button class="btn btn-primary" on:click={openCreate}>＋ New disbursement</button>{/if}</div>
<section class="card"><div class="filters"><div class="filter-field"><label class="field-label">Status</label><select bind:value={statusFilter} on:change={() => { page = 1; load(); }}><option value="">All statuses</option><option value="SCHEDULED">Scheduled</option><option value="PAID">Paid</option><option value="CANCELLED">Cancelled</option></select></div></div>{#if loading}<Loading />{:else if error}<ErrorState message={error} retry={load} />{:else if rows.length}<div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Church</th><th>Period</th><th>Amount</th><th>Status</th><th>Prepared by</th><th></th></tr></thead><tbody>{#each rows as row}<tr><td class="receipt-code">{row.reference}</td><td><strong>{row.church_name}</strong><small class="subtext">{row.payment_method || "No method"}</small></td><td class="nowrap">{dateOnly(row.period_start)} – {dateOnly(row.period_end)}</td><td class="money">{money(row.amount_usd)}</td><td><StatusBadge status={row.status} />{#if row.paid_at}<small class="subtext">{dateTime(row.paid_at)}</small>{/if}</td><td>{row.prepared_by_username || "—"}</td><td class="table-actions">{#if writable && row.status !== "PAID"}<button class="btn btn-small btn-success" on:click={() => pay(row)}>Mark paid</button>{/if}{#if writable}<button class="btn btn-small" on:click={() => openEdit(row)}>Edit</button>{/if}</td></tr>{/each}</tbody></table></div><Pagination count={total} page={page} pageSize={50} onPage={(next) => { page = next; load(); }} />{:else}<EmptyState message="No disbursements found." />{/if}</section>

<Modal bind:open={modalOpen} title={`${editing ? "Edit" : "New"} disbursement`} onClose={close}>{#if formError}<div class="form-error">{formError}</div>{/if}<form class="form-grid" on:submit|preventDefault={save}><div class="form-field full"><label class="field-label required">Church</label><select class="field" bind:value={form.church} required><option value="">Select church</option>{#each churches as church}<option value={church.id}>{church.name} · {church.station_name}</option>{/each}</select></div><div class="form-field"><label class="field-label required">Period start</label><input class="field" type="date" bind:value={form.period_start} required /></div><div class="form-field"><label class="field-label required">Period end</label><input class="field" type="date" bind:value={form.period_end} required /></div><div class="form-field"><label class="field-label required">Amount USD</label><input class="field" type="number" min="0" step="0.01" bind:value={form.amount_usd} required /></div><div class="form-field"><label class="field-label">Amount CDF</label><input class="field" type="number" min="0" step="0.01" bind:value={form.amount_cdf} /></div><div class="form-field"><label class="field-label">Status</label><select class="field" bind:value={form.status}><option value="SCHEDULED">Scheduled</option><option value="PAID">Paid</option><option value="CANCELLED">Cancelled</option></select></div><div class="form-field"><label class="field-label">Payment method</label><input class="field" bind:value={form.payment_method} /></div><div class="form-field full"><label class="field-label">Notes</label><textarea class="field" bind:value={form.notes}></textarea></div><div class="form-actions form-field full"><button class="btn" type="button" on:click={close}>Cancel</button><button class="btn btn-primary" disabled={busy}>{busy ? "Saving…" : "Save"}</button></div></form></Modal>

<style>.subtext{display:block;color:var(--muted);font-size:10px;margin-top:3px}.table-actions{justify-content:flex-end}</style>
