<script lang="ts">
  import { onMount } from "svelte";
  import { driversApi } from "../lib/api";
  import { dateTime, money } from "../lib/format";
  import { navigate, routePath } from "../lib/router";
  import type { Driver, Transaction } from "../lib/types";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import Loading from "../lib/components/Loading.svelte";
  import StatusBadge from "../lib/components/StatusBadge.svelte";

  export let id: string;
  let driver: Driver | null = null; let transactions: Transaction[] = []; let summary: any = null; let qr = ""; let loading = true; let error = ""; let cardData: any = null;
  async function load(): Promise<void> { loading = true; error = ""; try { const response = await driversApi.get(id); driver = response.driver; transactions = response.transactions; summary = response.summary; qr = response.qr_code; } catch (err) { error = err instanceof Error ? err.message : "Unable to load driver."; } finally { loading = false; } }
  async function loadCard(): Promise<void> { try { cardData = await driversApi.idCard(id); } catch (err) { error = err instanceof Error ? err.message : "Unable to load ID card."; } }
  onMount(load);
</script>

{#if loading}<Loading />{:else if error && !driver}<ErrorState message={error} retry={load} />{:else if driver}
  <div class="page-heading"><div><h2>{driver.full_name || "Unknown driver"}</h2><p class="num">{driver.phone || "No phone"}</p></div><div class="heading-actions"><button class="btn" on:click={() => navigate(routePath("drivers"))}>← Back</button><button class="btn btn-primary" on:click={loadCard}>ID card</button>{#if cardData}<button class="btn" on:click={() => window.print()}>Print</button>{/if}</div></div>
  <div class="grid grid-3"><section class="card card-pad"><h3 class="section-title">Contact</h3><div class="detail-stack"><div><label>Phone</label><p>{driver.phone || "—"}</p></div><div><label>Email</label><p>{driver.email || "—"}</p></div><div><label>Gender</label><p>{driver.gender || "—"}</p></div><div><label>Marital status</label><p>{driver.marital_status || "—"}</p></div></div></section><section class="card card-pad"><h3 class="section-title">Location</h3><div class="detail-stack"><div><label>Commune</label><p>{driver.commune || "—"}</p></div><div><label>Quartier</label><p>{driver.quartier || "—"}</p></div><div><label>City / country</label><p>{driver.city_country || "—"}</p></div></div></section><section class="card card-pad"><h3 class="section-title">Vehicle</h3><div class="detail-stack"><div><label>Type</label><p>{driver.vehicle_type || "—"}</p></div><div><label>Color</label><p>{driver.vehicle_color || "—"}</p></div><div><label>Fuel</label><p>{driver.fuel_type || "—"}</p></div><div><label>Litres/day</label><p>{driver.daily_fuel_consumption || "—"}</p></div></div></section></div>
  <div class="grid grid-wide" style="margin-top:16px"><section class="card card-pad"><h3 class="section-title">OSS health program</h3><div class="detail-grid" style="margin-top:16px"><div class="detail-item"><label>Health coverage</label><p>{driver.has_health_coverage === true ? "Yes" : driver.has_health_coverage === false ? "No" : "Unknown"}</p></div><div class="detail-item"><label>Care access difficulty</label><p>{driver.has_care_access_difficulty === true ? "Yes" : driver.has_care_access_difficulty === false ? "No" : "Unknown"}</p></div><div class="detail-item"><label>Dependents</label><p>{driver.dependents || "—"}</p></div><div class="detail-item"><label>Field agent</label><p>{driver.field_agent || "—"}</p></div><div class="detail-item"><label>Registration date</label><p>{driver.registration_date || "—"}</p></div><div class="detail-item"><label>Consent</label><p>{driver.consent ? "Given" : "—"}</p></div></div></section><section class="card card-pad qr-box"><h3 class="section-title">Profile QR</h3>{#if qr}<img class="qr-preview" src={qr} alt="Driver profile QR code" />{:else}<p class="muted">QR unavailable.</p>{/if}</section></div>
  <div class="kpi-grid" style="margin-top:16px"><div class="kpi-card"><p class="kpi-label">Levies</p><p class="kpi-value">{summary?.count || 0}</p></div><div class="kpi-card tone-success"><p class="kpi-label">Total levy</p><p class="kpi-value money">{money(summary?.total_levy_usd)}</p></div><div class="kpi-card"><p class="kpi-label">Total amount</p><p class="kpi-value money">{money(summary?.total_amount_usd)}</p></div><div class="kpi-card"><p class="kpi-label">Registered</p><p class="kpi-value" style="font-size:15px">{driver.registration_date || "—"}</p></div></div>
  {#if cardData}<section class="card card-pad print-card"><div class="split"><div><p class="kpi-label">Driver ID card</p><h3>{cardData.card_number}</h3><p class="muted">Valid {cardData.delivery} → {cardData.expiration}</p></div><img class="image-preview" src={cardData.kd_logo as string} alt="Logo" /></div><div class="card-id-media"><img class="qr-preview" src={cardData.qr_code as string} alt="QR code" />{#if cardData.barcode}<img class="barcode" src={cardData.barcode as string} alt="Barcode" />{/if}</div></section>{/if}
  <section class="card" style="margin-top:16px"><div class="card-header"><div><h3>Levy history</h3><p>Transactions matched by normalized driver phone</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Receipt</th><th>Station</th><th>Amount</th><th>Levy</th><th>Status</th><th>Date</th></tr></thead><tbody>{#each transactions as tx}<tr><td><a class="text-link receipt-code" href={routePath("transaction-detail", tx.id)} on:click={(event) => { event.preventDefault(); navigate(routePath("transaction-detail", tx.id)); }}>{tx.receipt_code}</a></td><td>{tx.station_name}</td><td>{money(tx.amount_usd)}</td><td class="money">{money(tx.levy_amount_usd)}</td><td><StatusBadge status={tx.status} /></td><td class="muted nowrap">{dateTime(tx.created_at)}</td></tr>{:else}<tr><td colspan="6"><div class="empty-state">No levy history.</div></td></tr>{/each}</tbody></table></div></section>
{:else}<div class="empty-state">Driver not found.</div>{/if}

<style>
  .detail-stack{display:flex;flex-direction:column;gap:14px;margin-top:16px}.detail-stack label{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;font-weight:700;letter-spacing:.05em}.detail-stack p{font-size:13px;margin:4px 0 0}.qr-box{text-align:center}.qr-box .section-title{text-align:left}.card-id-media{display:flex;align-items:center;gap:30px;margin-top:20px}.barcode{max-width:280px;max-height:80px}.print-card{border:2px solid var(--accent)}@media print{.sidebar,.topbar,.page-heading,.kpi-grid,.grid,.card:not(.print-card){display:none!important}.main-content{padding:0}.print-card{display:block!important}}
</style>
