<script lang="ts">
  import { onMount } from "svelte";
  import { driversApi } from "../lib/api";
  import { navigate, routePath } from "../lib/router";
  import { numberValue } from "../lib/format";
  import type { Driver, DriverListResponse } from "../lib/types";
  import BarChart from "../lib/components/BarChart.svelte";
  import DonutChart from "../lib/components/DonutChart.svelte";
  import EmptyState from "../lib/components/EmptyState.svelte";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import Loading from "../lib/components/Loading.svelte";
  import Pagination from "../lib/components/Pagination.svelte";

  let response: DriverListResponse | null = null; let rows: Driver[] = []; let loading = true; let error = ""; let page = 1;
  let filters = { q: "", commune: "", vehicle_type: "", fuel_type: "", agent: "" }; let sort = "name"; let dir = "asc";
  async function load(): Promise<void> { loading = true; error = ""; try { response = await driversApi.list({ ...filters, sort, dir, page, page_size: 50 }); rows = response.results; } catch (err) { error = err instanceof Error ? err.message : "Unable to load drivers."; } finally { loading = false; } }
  function apply(): void { page = 1; load(); }
  function reset(): void { filters = { q: "", commune: "", vehicle_type: "", fuel_type: "", agent: "" }; apply(); }
  function sortBy(value: string): void { if (sort === value) dir = dir === "asc" ? "desc" : "asc"; else { sort = value; dir = "asc"; } load(); }
  async function exportExcel(): Promise<void> { const blob = await driversApi.exportExcel(filters); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "LCI_drivers.xlsx"; anchor.click(); URL.revokeObjectURL(url); }
  onMount(load);
  $: options = response?.filter_options;
  $: kpi = response?.kpi;
</script>

<div class="page-heading"><div><h2>Drivers</h2><p>OSS registration directory and levy-linked profiles.</p></div><button class="btn" on:click={exportExcel}>⇩ Excel</button></div>
<section class="card"><form class="filters" on:submit|preventDefault={apply}><div class="filter-field search-field"><label class="field-label">Search</label><input bind:value={filters.q} placeholder="Name, phone, email…" /></div><div class="filter-field"><label class="field-label">Commune</label><select bind:value={filters.commune}><option value="">All communes</option>{#each options?.communes || [] as value}<option value={value}>{value}</option>{/each}</select></div><div class="filter-field"><label class="field-label">Vehicle</label><select bind:value={filters.vehicle_type}><option value="">All vehicles</option>{#each options?.vehicle_types || [] as value}<option value={value}>{value}</option>{/each}</select></div><div class="filter-field"><label class="field-label">Fuel</label><select bind:value={filters.fuel_type}><option value="">All fuel types</option>{#each options?.fuel_types || [] as value}<option value={value}>{value}</option>{/each}</select></div><div class="filter-field"><label class="field-label">Field agent</label><select bind:value={filters.agent}><option value="">All agents</option>{#each options?.agents || [] as value}<option value={value}>{value}</option>{/each}</select></div><div class="button-group"><button class="btn btn-primary" type="submit">Apply</button><button class="btn btn-quiet" type="button" on:click={reset}>Clear</button></div></form>
{#if loading}<Loading />{:else if error}<ErrorState message={error} retry={load} />{:else if response}<div class="driver-kpis"><div><span>Filtered</span><strong>{kpi?.filtered || 0}</strong></div><div><span>Total drivers</span><strong>{kpi?.total || 0}</strong></div><div><span>Top vehicle</span><strong>{kpi?.top_vehicle || "—"}</strong><small>{kpi?.top_vehicle_n || 0} registrations</small></div><div><span>Health coverage</span><strong>{kpi?.coverage_pct || 0}%</strong></div><div><span>Field agents</span><strong>{kpi?.agents || 0}</strong></div></div><div class="driver-charts"><div class="card card-pad"><h3 class="section-title">Vehicles</h3><BarChart items={(response.charts.vehicle || []).map(([label, value]) => ({ label, value }))} /></div><div class="card card-pad"><h3 class="section-title">Registration by commune</h3><BarChart items={(response.charts.commune || []).map(([label, value]) => ({ label, value }))} color="#15803d" /></div><div class="card card-pad"><h3 class="section-title">Health coverage</h3><DonutChart values={response.charts.health || []} labels={["Yes", "No", "Unknown"]} /></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th><button class="sort-button" on:click={() => sortBy("name")}>Name {sort === "name" ? (dir === "asc" ? "↑" : "↓") : ""}</button></th><th><button class="sort-button" on:click={() => sortBy("commune")}>Commune</button></th><th><button class="sort-button" on:click={() => sortBy("vehicle")}>Vehicle</button></th><th>Fuel</th><th>Phone</th><th>Coverage</th><th>Agent</th></tr></thead><tbody>{#each rows as driver}<tr><td><a class="text-link" href={routePath("driver-detail", driver.id)} on:click={(event) => { event.preventDefault(); navigate(routePath("driver-detail", driver.id)); }}><strong>{driver.full_name || "Unknown"}</strong></a><small class="subtext">{driver.email || "No email"}</small></td><td>{driver.commune || "—"}</td><td>{driver.vehicle_type || "—"}</td><td>{driver.fuel_type || "—"}</td><td class="num">{driver.phone || "—"}</td><td>{driver.has_health_coverage === true ? "Yes" : driver.has_health_coverage === false ? "No" : "—"}</td><td>{driver.field_agent || "—"}</td></tr>{:else}<tr><td colspan="7"><EmptyState message="No drivers found." /></td></tr>{/each}</tbody></table></div><Pagination count={response.count} page={page} pageSize={50} onPage={(next) => { page = next; load(); }} />{/if}</section>

<style>.driver-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:1px;border-bottom:1px solid var(--line);background:var(--line)}.driver-kpis>div{background:var(--surface);padding:14px 16px}.driver-kpis span,.driver-kpis small{display:block;font-size:10px;color:var(--muted)}.driver-kpis strong{display:block;font:600 20px "IBM Plex Mono",monospace;margin-top:7px}.driver-kpis small{margin-top:3px}.driver-charts{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;padding:16px 0}.sort-button{border:0;background:none;padding:0;color:inherit;font:inherit;text-transform:inherit;letter-spacing:inherit;font-weight:inherit;cursor:pointer}.subtext{display:block;color:var(--muted);font-size:10px;margin-top:3px}@media(max-width:900px){.driver-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.driver-charts{grid-template-columns:1fr}}</style>
