<script lang="ts">
  import { onMount } from "svelte";
  import { churchesApi, companiesApi, stationsApi } from "../lib/api";
  import { dateTime, money } from "../lib/format";
  import { navigate, routePath } from "../lib/router";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import Loading from "../lib/components/Loading.svelte";
  import StatusBadge from "../lib/components/StatusBadge.svelte";
  import type { Church, Company, Station, Transaction } from "../lib/types";

  export let resource: "companies" | "stations" | "churches";
  export let id: string;
  let item: any = null; let loading = true; let error = "";
  $: title = resource === "companies" ? "Company detail" : resource === "stations" ? "Station detail" : "Church detail";
  async function load(): Promise<void> { loading = true; error = ""; try { item = resource === "companies" ? await companiesApi.get(id) : resource === "stations" ? await stationsApi.get(id) : await churchesApi.get(id); } catch (err) { error = err instanceof Error ? err.message : "Unable to load details."; } finally { loading = false; } }
  onMount(load);
</script>

{#if loading}<Loading />{:else if error}<ErrorState message={error} retry={load} />{:else if item}
  <div class="page-heading"><div><h2>{title}</h2><p>{item.name}</p></div><button class="btn" on:click={() => navigate(routePath(resource))}>← Back</button></div>
  <section class="card card-pad"><div class="split"><div><p class="kpi-label">{resource === "companies" ? "Company" : resource === "stations" ? "Station" : "Church"}</p><h3 style="font-size:22px;margin:5px 0">{item.name}</h3><p class="muted receipt-code">{item.code || item.station_name || ""}</p></div><span class="status" class:status-verified={item.is_active} class:status-cancelled={!item.is_active}>{item.is_active ? "Active" : "Inactive"}</span></div><div class="detail-grid" style="margin-top:24px"><div class="detail-item"><label>Contact</label><p>{resource === "companies" ? item.contact_email || "—" : resource === "churches" ? item.contact_person || "—" : item.company_name}</p></div><div class="detail-item"><label>Phone</label><p>{resource === "companies" ? item.contact_phone || "—" : resource === "churches" ? item.contact_phone || "—" : item.address || "—"}</p></div><div class="detail-item"><label>Created</label><p>{dateTime(item.created_at)}</p></div></div></section>
  {#if resource === "companies"}<section class="card" style="margin-top:16px"><div class="card-header"><div><h3>Stations</h3><p>{item.stations?.length || 0} active stations</p></div><div class="money">{money(item.totals?.total_usd)}</div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Station</th><th>Code</th><th>Transactions</th><th>Levy</th></tr></thead><tbody>{#each item.stations || [] as station}<tr><td><a class="text-link" href={routePath("station-detail", station.id)} on:click={(event) => { event.preventDefault(); navigate(routePath("station-detail", station.id)); }}>{station.name}</a></td><td class="receipt-code">{station.code}</td><td>{station.tx_count || 0}</td><td class="money">{money(station.total_levy)}</td></tr>{:else}<tr><td colspan="4"><div class="empty-state">No stations.</div></td></tr>{/each}</tbody></table></div></section>{/if}
  {#if resource === "stations"}<section class="grid grid-2" style="margin-top:16px"><div class="card"><div class="card-header"><h3>Churches</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Beneficiaries</th></tr></thead><tbody>{#each item.churches || [] as church}<tr><td><a class="text-link" href={routePath("church-detail", church.id)} on:click={(event) => { event.preventDefault(); navigate(routePath("church-detail", church.id)); }}>{church.name}</a></td><td>{church.beneficiary_count}</td></tr>{:else}<tr><td colspan="2"><div class="empty-state">No churches.</div></td></tr>{/each}</tbody></table></div></div><div class="card"><div class="card-header"><h3>Recent transactions</h3><span class="money">{money(item.totals?.total_usd)}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Receipt</th><th>Levy</th><th>Status</th></tr></thead><tbody>{#each item.recent_transactions || [] as tx}<tr><td><a class="text-link receipt-code" href={routePath("transaction-detail", tx.id)} on:click={(event) => { event.preventDefault(); navigate(routePath("transaction-detail", tx.id)); }}>{tx.receipt_code}</a></td><td class="money">{money(tx.levy_amount_usd)}</td><td><StatusBadge status={tx.status} /></td></tr>{:else}<tr><td colspan="3"><div class="empty-state">No transactions.</div></td></tr>{/each}</tbody></table></div></div></section>{/if}
  {#if resource === "churches"}<section class="grid grid-2" style="margin-top:16px"><div class="card card-pad"><p class="kpi-label">Total levy</p><p class="kpi-value money">{money(item.totals?.levy)}</p><p class="muted">{item.totals?.count || 0} transactions</p></div><div class="card card-pad"><p class="kpi-label">Disbursements</p><p class="kpi-value">{item.disbursements?.length || 0}</p><p class="muted">Recent records</p></div></section><section class="card" style="margin-top:16px"><div class="card-header"><h3>Recent transactions</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Receipt</th><th>Amount</th><th>Levy</th><th>Status</th></tr></thead><tbody>{#each item.transactions || [] as tx}<tr><td class="receipt-code">{tx.receipt_code}</td><td>{money(tx.amount_usd)}</td><td class="money">{money(tx.levy_amount_usd)}</td><td><StatusBadge status={tx.status} /></td></tr>{:else}<tr><td colspan="4"><div class="empty-state">No transactions.</div></td></tr>{/each}</tbody></table></div></section>{/if}
{:else}<div class="empty-state">Record not found.</div>{/if}
