<script lang="ts">
  import { verifyApi } from "../lib/api";
  import { dateTime, money } from "../lib/format";
  import StatusBadge from "../lib/components/StatusBadge.svelte";
  let code = ""; let result: any = null; let error = ""; let loading = false;
  async function verify(): Promise<void> { if (!code.trim()) return; loading = true; result = null; error = ""; try { result = await verifyApi.receipt(code.trim()); } catch (err) { error = err instanceof Error ? err.message : "Receipt not found."; } finally { loading = false; } }
</script>

<div class="page-heading"><div><h2>Verify receipt</h2><p>Confirm a receipt code independently of the current dashboard scope.</p></div></div><section class="card card-pad verify-card"><form class="verify-form" on:submit|preventDefault={verify}><input class="field receipt-code" bind:value={code} placeholder="LCI-XXXX-XXXX-CKSM" aria-label="Receipt code" /><button class="btn btn-primary" disabled={loading}>{loading ? "Checking…" : "Verify"}</button></form>{#if error}<div class="alert alert-error" style="margin-top:16px">{error}</div>{/if}{#if result}<div class:invalid={!result.valid} class="verify-result">{#if result.valid}<div class="verify-icon">✓</div><div><h3>Receipt is valid</h3><p class="muted receipt-code">{result.receipt_code}</p><div class="detail-grid"><div class="detail-item"><label>Company</label><p>{result.company}</p></div><div class="detail-item"><label>Station</label><p>{result.station}</p></div><div class="detail-item"><label>Church</label><p>{result.church}</p></div><div class="detail-item"><label>Amount</label><p>{money(result.amount_usd)}</p></div><div class="detail-item"><label>Levy</label><p class="money">{money(result.levy_usd)}</p></div><div class="detail-item"><label>Status</label><p><StatusBadge status={String(result.status)} /></p></div><div class="detail-item"><label>Created</label><p>{dateTime(String(result.created_at))}</p></div></div></div>{:else}<div class="verify-icon invalid-icon">×</div><div><h3>Receipt not found</h3><p class="muted">Check the code and try again.</p></div>{/if}</div>{/if}</section>

<style>.verify-card{max-width:900px}.verify-form{display:flex;gap:10px}.verify-form .field{flex:1}.verify-result{display:flex;gap:16px;align-items:flex-start;margin-top:22px;padding:18px;border:1px solid var(--ok);background:var(--ok-soft);border-radius:9px}.verify-result.invalid{border-color:var(--danger);background:var(--danger-soft)}.verify-result h3{margin:0 0 4px;font-size:15px}.verify-icon{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:var(--ok);color:#fff;font-size:20px;font-weight:700;flex-shrink:0}.invalid-icon{background:var(--danger)}@media(max-width:600px){.verify-form{display:block}.verify-form .btn{width:100%;margin-top:8px}}
</style>
