import React, { createContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Language = "en" | "fr" | "sw";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "theme.light": "Light",
    "theme.dark": "Dark",
    "language.english": "English",
    "language.french": "Français",
    "language.swahili": "Swahili",
    "transaction.success": "Transaction Posted",
    "transaction.offline": "Saved Offline",
    "transaction.summary": "Transaction Summary",
    "transaction.posted": "Transaction recorded and submitted to the LCI server.",
    "transaction.offline.msg": "No connection — saved locally and will sync automatically when you're back online.",
    "receipt.code": "RECEIPT CODE",
    "receipt.local": "LOCAL REFERENCE",
    "receipt.verify": "Present to NGO for verification",
    "receipt.preview": "Receipt Preview",
    "receipt.print": "Print Receipt",
    "receipt.sync.msg": "Receipt code assigned after sync",
    "church": "Church",
    "company": "Company",
    "station": "Station",
    "fuel.type": "Fuel Type",
    "amount.usd": "Amount (USD)",
    "amount.cdf": "Amount (CDF)",
    "levy": "2% Charity Levy",
    "back": "Back to Home",
    "login": "Login",
    "logout": "Logout",
    "username": "Username",
    "password": "Password",
    "settings": "Settings",
    "theme": "Theme",
    "language": "Language",
    "cancel": "Cancel",
    "loading": "Loading…",
    "online": "Online",
    "offline": "Offline",
    "synced": "Synced",
    "pending": "Pending",

    "nav.home": "Home",
    "nav.history": "History",
    "nav.history.title": "Transaction History",
    "nav.scan": "Scan",
    "nav.scan.title": "Scan Driver",
    "nav.analytics": "Analytics",
    "nav.analytics.title": "My Analytics",
    "nav.profile": "Profile",
    "nav.profile.title": "My Profile",

    "home.greeting.morning": "Good morning",
    "home.greeting.afternoon": "Good afternoon",
    "home.greeting.evening": "Good evening",
    "home.sync.complete": "Sync Complete",
    "home.sync.synced": "synced",
    "home.sync.failed": "failed",
    "home.sync.failed.title": "Sync Failed",
    "home.syncing": "Syncing…",
    "home.pending.tap": "pending — Tap to sync",
    "home.today": "Today",
    "home.today.levy": "Today's Levy",
    "home.pending": "Pending",
    "home.live.rate": "LIVE RATE",
    "home.rate.unavailable": "Rate unavailable",
    "home.new.transaction": "New Transaction",
    "home.new.transaction.sub": "Record a fuel sale with 2% levy",
    "home.verify.receipt": "Verify Receipt",
    "home.all.history": "All History",
    "home.this.month": "This Month",
    "home.transactions": "Transactions",
    "home.levy.collected": "Levy Collected",
    "home.synced": "Synced",
    "home.total.alltime": "Total All-Time",
    "home.recent": "Recent",
    "home.see.all": "See all",
    "home.levy.footer": "2% charity levy supports the LCI humanitarian fund",

    "history.levy": "levy",
    "history.filter.all": "All",
    "history.filter.synced": "Synced",
    "history.filter.pending": "Pending",
    "history.records": "records",
    "history.search.placeholder": "Search church, fuel, receipt…",
    "history.empty.nomatch": "No matching transactions",
    "history.empty.none": "No transactions yet",
    "history.empty.nomatch.sub": "Try adjusting your search or filter",
    "history.empty.none.sub": "Your first sale will appear here",

    "scan.permission.title": "Camera access needed",
    "scan.permission.subtitle": "Freddy uses the camera to scan a driver's ID card QR code and pull up their levy history.",
    "scan.permission.grant": "Grant permission",
    "scan.hint": "Point the camera at the driver's QR code",

    "analytics.today": "Today",
    "analytics.this.month": "This Month",
    "analytics.all.time": "All Time",
    "analytics.transactions": "Transactions",
    "analytics.levy.collected": "Levy Collected",
    "analytics.avg.per.tx": "Avg per Tx",
    "analytics.sync.status": "Sync Status",
    "analytics.total": "Total",
    "analytics.synced.pct": "synced",
    "analytics.top.churches": "Top Churches",
    "analytics.levy.lower": "levy",
    "analytics.by.fuel.type": "By Fuel Type",
    "analytics.levy.programme": "Charity Levy Programme",
    "analytics.levy.programme.body": "Every fuel transaction you record contributes a 2% levy to the LCI humanitarian fund. Your work directly supports communities in Lubumbashi.",
    "analytics.total.contributed": "Total contributed",
    "analytics.levy.rate": "Levy rate",

    "profile.signout": "Sign Out",
    "profile.signout.confirm": "Are you sure you want to sign out?",
    "profile.role.agent": "Field Agent",
    "profile.role.manager": "Station Manager",
    "profile.role.admin": "Administrator",
    "profile.role.auditor": "Auditor",
    "profile.levy.raised": "Levy Raised",
    "profile.assignment": "Assignment",
    "profile.quick.actions": "Quick Actions",
    "profile.verify.receipt": "Verify a Receipt",
    "profile.verify.receipt.sub": "Check any LCI receipt code",
    "profile.settings.sub": "Theme, language, and printer",
    "profile.pending.tx": "View Pending Transactions",
    "profile.pending.tx.sub": "Records awaiting sync",
    "profile.about": "About",
    "profile.app": "App",
    "profile.version": "Version",
    "profile.levy.rate": "Levy Rate",
    "profile.programme": "Programme",

    "login.missing.fields": "Missing fields",
    "login.missing.fields.body": "Enter your username and password.",
    "login.failed": "Login failed",
    "login.failed.body": "Invalid credentials. Please try again.",
    "login.welcome": "Welcome back",
    "login.welcome.sub": "Sign in to your agent account",
    "login.username.placeholder": "Enter your username",
    "login.password.placeholder": "Enter your password",
    "login.signin": "Sign In",
    "login.footer": "Secure · Offline-capable · 2% Charity Levy",

    "newtx.step.fueltype": "Fuel Type",
    "newtx.step.amount": "Amount",
    "newtx.step.preview": "Preview",
    "newtx.select.fueltype": "Select Fuel Type",
    "newtx.select.church": "Select Church",
    "newtx.next": "Next →",
    "newtx.enter.amount": "Enter Amount",
    "newtx.amount.in": "Amount in",
    "newtx.live.breakdown": "Live Breakdown",
    "newtx.for": "For",
    "newtx.driver.phone": "Driver phone (optional)",
    "newtx.driver.phone.hint": "Links this levy to the driver so it shows in their history when scanned.",
    "newtx.notes": "Notes (optional)",
    "newtx.back": "← Back",
    "newtx.review": "Review →",
    "newtx.confirm": "Confirm Transaction",
    "newtx.currency": "Currency",
    "newtx.edit": "← Edit",
    "newtx.submit": "Submit Transaction",

    "detail.not.found": "Transaction not found",
    "detail.go.back": "Go Back",
    "detail.synced": "Synced to server",
    "detail.pending": "Pending sync — will upload when online",
    "detail.transaction.details": "Transaction Details",
    "detail.est": "est.",
    "detail.timestamp": "Timestamp",
    "detail.date": "Date",
    "detail.time": "Time",
    "detail.back.history": "Back to History",

    "verify.title": "Verify Receipt",
    "verify.subtitle": "Enter the LCI receipt code to confirm a transaction is authentic",
    "verify.not.found": "Receipt not found. Check the code and try again.",
    "verify.valid": "Valid Receipt",
    "verify.valid.sub": "This transaction is authentic",
    "verify.amount": "Amount",
    "verify.status": "Status",

    "driver.not.found": "Driver not found.",
    "driver.unknown": "Unknown driver",
    "driver.total.levy": "Total levy",
    "driver.total.fuel": "Total fuel",
    "driver.record.purchase": "Record a purchase",
    "driver.new.purchase": "New purchase",
    "driver.no.phone.warn": "No phone on file — won't link to history.",
    "driver.amount.purchased": "Amount purchased",
    "driver.contribution": "Contribution (2%)",
    "driver.auto.calculated": "Auto-calculated",
    "driver.receiving.church": "Receiving church",
    "driver.no.church": "No church available for your station.",
    "driver.save.purchase": "Save purchase",
    "driver.previous.tx": "Previous transactions",
    "driver.no.tx": "No levy transactions recorded for this driver yet.",
    "driver.fuel": "fuel",
    "driver.recorded": "Recorded",
    "driver.recorded.body": "Purchase and 2% contribution saved.",
    "driver.saved.offline": "Saved offline",
    "driver.saved.offline.body": "No connection right now — it will sync automatically and appear in this driver's history once synced.",
    "driver.couldnt.load": "Couldn't load driver",
    "driver.unknown.error": "Unknown error.",
    "driver.back.scan": "Back to scan",

    "printer.list.error": "Could not list Bluetooth devices.",
    "printer.set": "Printer Set",
    "printer.set.body": "will be used for receipts.",
    "printer.print.failed": "Print Failed",
    "printer.print.failed.body": "Could not reach the printer.",
    "printer.intro": "Pair your 58mm thermal printer in Android Bluetooth settings first, then select it below. Receipts print directly to this printer.",
    "printer.active": "ACTIVE PRINTER",
    "printer.test": "Test Print",
    "printer.forget": "Forget",
    "printer.paired.devices": "Paired Devices",
    "printer.no.devices": "No paired Bluetooth devices found. Pair your printer in Android Settings, then tap refresh.",
    "printer.unknown.device": "Unknown device",
    "printer.done": "Done",
    "printer.retry": "Retry",
  },
  fr: {
    "theme.light": "Clair",
    "theme.dark": "Sombre",
    "language.english": "English",
    "language.french": "Français",
    "language.swahili": "Swahili",
    "transaction.success": "Transaction Publiée",
    "transaction.offline": "Enregistré Hors Ligne",
    "transaction.summary": "Résumé de la Transaction",
    "transaction.posted": "Transaction enregistrée et soumise au serveur LCI.",
    "transaction.offline.msg": "Pas de connexion — enregistré localement et sera synchronisé automatiquement lorsque vous êtes en ligne.",
    "receipt.code": "CODE DE REÇU",
    "receipt.local": "RÉFÉRENCE LOCALE",
    "receipt.verify": "Présenter à l'ONG pour vérification",
    "receipt.preview": "Aperçu du Reçu",
    "receipt.print": "Imprimer le Reçu",
    "receipt.sync.msg": "Code de reçu assigné après la synchronisation",
    "church": "Église",
    "company": "Entreprise",
    "station": "Station",
    "fuel.type": "Type de Carburant",
    "amount.usd": "Montant (USD)",
    "amount.cdf": "Montant (CDF)",
    "levy": "Prélèvement Caritatif 2%",
    "back": "Retour à l'Accueil",
    "login": "Connexion",
    "logout": "Déconnexion",
    "username": "Nom d'utilisateur",
    "password": "Mot de passe",
    "settings": "Paramètres",
    "theme": "Thème",
    "language": "Langue",
    "cancel": "Annuler",
    "loading": "Chargement…",
    "online": "En ligne",
    "offline": "Hors ligne",
    "synced": "Synchronisé",
    "pending": "En attente",

    "nav.home": "Accueil",
    "nav.history": "Historique",
    "nav.history.title": "Historique des Transactions",
    "nav.scan": "Scanner",
    "nav.scan.title": "Scanner un Chauffeur",
    "nav.analytics": "Analyses",
    "nav.analytics.title": "Mes Analyses",
    "nav.profile": "Profil",
    "nav.profile.title": "Mon Profil",

    "home.greeting.morning": "Bonjour",
    "home.greeting.afternoon": "Bon après-midi",
    "home.greeting.evening": "Bonsoir",
    "home.sync.complete": "Synchronisation Terminée",
    "home.sync.synced": "synchronisées",
    "home.sync.failed": "échouées",
    "home.sync.failed.title": "Échec de Synchronisation",
    "home.syncing": "Synchronisation…",
    "home.pending.tap": "en attente — Toucher pour synchroniser",
    "home.today": "Aujourd'hui",
    "home.today.levy": "Prélèvement du Jour",
    "home.pending": "En attente",
    "home.live.rate": "TAUX EN DIRECT",
    "home.rate.unavailable": "Taux indisponible",
    "home.new.transaction": "Nouvelle Transaction",
    "home.new.transaction.sub": "Enregistrer une vente de carburant avec 2% de prélèvement",
    "home.verify.receipt": "Vérifier un Reçu",
    "home.all.history": "Tout l'Historique",
    "home.this.month": "Ce Mois",
    "home.transactions": "Transactions",
    "home.levy.collected": "Prélèvement Collecté",
    "home.synced": "Synchronisées",
    "home.total.alltime": "Total Général",
    "home.recent": "Récent",
    "home.see.all": "Voir tout",
    "home.levy.footer": "Le prélèvement caritatif de 2% soutient le fonds humanitaire LCI",

    "history.levy": "prélèvement",
    "history.filter.all": "Tous",
    "history.filter.synced": "Synchronisé",
    "history.filter.pending": "En attente",
    "history.records": "enregistrements",
    "history.search.placeholder": "Rechercher église, carburant, reçu…",
    "history.empty.nomatch": "Aucune transaction correspondante",
    "history.empty.none": "Aucune transaction pour le moment",
    "history.empty.nomatch.sub": "Essayez d'ajuster votre recherche ou filtre",
    "history.empty.none.sub": "Votre première vente apparaîtra ici",

    "scan.permission.title": "Accès à la caméra requis",
    "scan.permission.subtitle": "Freddy utilise la caméra pour scanner le QR code de la carte d'identité d'un chauffeur et afficher son historique de prélèvement.",
    "scan.permission.grant": "Autoriser l'accès",
    "scan.hint": "Pointez la caméra vers le QR code du chauffeur",

    "analytics.today": "Aujourd'hui",
    "analytics.this.month": "Ce Mois",
    "analytics.all.time": "Depuis le Début",
    "analytics.transactions": "Transactions",
    "analytics.levy.collected": "Prélèvement Collecté",
    "analytics.avg.per.tx": "Moy. par Transaction",
    "analytics.sync.status": "État de Synchronisation",
    "analytics.total": "Total",
    "analytics.synced.pct": "synchronisé",
    "analytics.top.churches": "Meilleures Églises",
    "analytics.levy.lower": "prélèvement",
    "analytics.by.fuel.type": "Par Type de Carburant",
    "analytics.levy.programme": "Programme de Prélèvement Caritatif",
    "analytics.levy.programme.body": "Chaque transaction de carburant que vous enregistrez contribue un prélèvement de 2% au fonds humanitaire LCI. Votre travail soutient directement les communautés de Lubumbashi.",
    "analytics.total.contributed": "Total contribué",
    "analytics.levy.rate": "Taux de prélèvement",

    "profile.signout": "Se Déconnecter",
    "profile.signout.confirm": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "profile.role.agent": "Agent de Terrain",
    "profile.role.manager": "Gestionnaire de Station",
    "profile.role.admin": "Administrateur",
    "profile.role.auditor": "Auditeur",
    "profile.levy.raised": "Prélèvement Collecté",
    "profile.assignment": "Affectation",
    "profile.quick.actions": "Actions Rapides",
    "profile.verify.receipt": "Vérifier un Reçu",
    "profile.verify.receipt.sub": "Vérifier n'importe quel code de reçu LCI",
    "profile.settings.sub": "Thème, langue et imprimante",
    "profile.pending.tx": "Voir les Transactions en Attente",
    "profile.pending.tx.sub": "Enregistrements en attente de synchronisation",
    "profile.about": "À Propos",
    "profile.app": "Application",
    "profile.version": "Version",
    "profile.levy.rate": "Taux de Prélèvement",
    "profile.programme": "Programme",

    "login.missing.fields": "Champs manquants",
    "login.missing.fields.body": "Entrez votre nom d'utilisateur et mot de passe.",
    "login.failed": "Échec de connexion",
    "login.failed.body": "Identifiants invalides. Veuillez réessayer.",
    "login.welcome": "Bon retour",
    "login.welcome.sub": "Connectez-vous à votre compte agent",
    "login.username.placeholder": "Entrez votre nom d'utilisateur",
    "login.password.placeholder": "Entrez votre mot de passe",
    "login.signin": "Se Connecter",
    "login.footer": "Sécurisé · Fonctionne Hors Ligne · Prélèvement Caritatif 2%",

    "newtx.step.fueltype": "Type de Carburant",
    "newtx.step.amount": "Montant",
    "newtx.step.preview": "Aperçu",
    "newtx.select.fueltype": "Sélectionner le Type de Carburant",
    "newtx.select.church": "Sélectionner l'Église",
    "newtx.next": "Suivant →",
    "newtx.enter.amount": "Entrer le Montant",
    "newtx.amount.in": "Montant en",
    "newtx.live.breakdown": "Répartition en Direct",
    "newtx.for": "Pour",
    "newtx.driver.phone": "Téléphone du chauffeur (optionnel)",
    "newtx.driver.phone.hint": "Associe ce prélèvement au chauffeur afin qu'il apparaisse dans son historique lors du scan.",
    "newtx.notes": "Notes (optionnel)",
    "newtx.back": "← Retour",
    "newtx.review": "Vérifier →",
    "newtx.confirm": "Confirmer la Transaction",
    "newtx.currency": "Devise",
    "newtx.edit": "← Modifier",
    "newtx.submit": "Soumettre la Transaction",

    "detail.not.found": "Transaction introuvable",
    "detail.go.back": "Retour",
    "detail.synced": "Synchronisé au serveur",
    "detail.pending": "Synchronisation en attente — sera téléchargé en ligne",
    "detail.transaction.details": "Détails de la Transaction",
    "detail.est": "est.",
    "detail.timestamp": "Horodatage",
    "detail.date": "Date",
    "detail.time": "Heure",
    "detail.back.history": "Retour à l'Historique",

    "verify.title": "Vérifier le Reçu",
    "verify.subtitle": "Entrez le code de reçu LCI pour confirmer qu'une transaction est authentique",
    "verify.not.found": "Reçu introuvable. Vérifiez le code et réessayez.",
    "verify.valid": "Reçu Valide",
    "verify.valid.sub": "Cette transaction est authentique",
    "verify.amount": "Montant",
    "verify.status": "Statut",

    "driver.not.found": "Chauffeur introuvable.",
    "driver.unknown": "Chauffeur inconnu",
    "driver.total.levy": "Prélèvement total",
    "driver.total.fuel": "Carburant total",
    "driver.record.purchase": "Enregistrer un achat",
    "driver.new.purchase": "Nouvel achat",
    "driver.no.phone.warn": "Aucun téléphone enregistré — ne sera pas lié à l'historique.",
    "driver.amount.purchased": "Montant acheté",
    "driver.contribution": "Contribution (2%)",
    "driver.auto.calculated": "Calculé automatiquement",
    "driver.receiving.church": "Église bénéficiaire",
    "driver.no.church": "Aucune église disponible pour votre station.",
    "driver.save.purchase": "Enregistrer l'achat",
    "driver.previous.tx": "Transactions précédentes",
    "driver.no.tx": "Aucune transaction de prélèvement enregistrée pour ce chauffeur.",
    "driver.fuel": "carburant",
    "driver.recorded": "Enregistré",
    "driver.recorded.body": "Achat et contribution de 2% enregistrés.",
    "driver.saved.offline": "Enregistré hors ligne",
    "driver.saved.offline.body": "Pas de connexion actuellement — cela se synchronisera automatiquement et apparaîtra dans l'historique de ce chauffeur une fois synchronisé.",
    "driver.couldnt.load": "Impossible de charger le chauffeur",
    "driver.unknown.error": "Erreur inconnue.",
    "driver.back.scan": "Retour au scan",

    "printer.list.error": "Impossible de lister les appareils Bluetooth.",
    "printer.set": "Imprimante Définie",
    "printer.set.body": "sera utilisée pour les reçus.",
    "printer.print.failed": "Échec de l'Impression",
    "printer.print.failed.body": "Impossible de joindre l'imprimante.",
    "printer.intro": "Associez d'abord votre imprimante thermique 58mm dans les paramètres Bluetooth Android, puis sélectionnez-la ci-dessous. Les reçus s'impriment directement sur cette imprimante.",
    "printer.active": "IMPRIMANTE ACTIVE",
    "printer.test": "Test d'Impression",
    "printer.forget": "Oublier",
    "printer.paired.devices": "Appareils Associés",
    "printer.no.devices": "Aucun appareil Bluetooth associé trouvé. Associez votre imprimante dans les paramètres Android, puis touchez actualiser.",
    "printer.unknown.device": "Appareil inconnu",
    "printer.done": "Terminé",
    "printer.retry": "Réessayer",
  },
  sw: {
    "theme.light": "Mwanga",
    "theme.dark": "Giza",
    "language.english": "English",
    "language.french": "Français",
    "language.swahili": "Swahili",
    "transaction.success": "Muamala Ulitumwa",
    "transaction.offline": "Umehifadhiwa Bila Mtandao",
    "transaction.summary": "Muhtasari wa Muamala",
    "transaction.posted": "Muamala umerekodiwa na kutumwa kwenye seva ya LCI.",
    "transaction.offline.msg": "Hakuna muunganisho — umehifadhiwa ndani na itasawazishwa kiotomatiki unapokuwako mtandaoni.",
    "receipt.code": "NAMBARI YA RISITI",
    "receipt.local": "REJELEO LA NDANI",
    "receipt.verify": "Toa kwa NGO kwa uthibitisho",
    "receipt.preview": "Muonekano wa Risiti",
    "receipt.print": "Chapisha Risiti",
    "receipt.sync.msg": "Nambari ya risiti imetengewa baada ya kusawazisha",
    "church": "Kanisa",
    "company": "Kampeni",
    "station": "Kituo",
    "fuel.type": "Aina ya Katabomba",
    "amount.usd": "Kiasi (USD)",
    "amount.cdf": "Kiasi (CDF)",
    "levy": "Zabuni Maombi 2%",
    "back": "Kurudi kwa Nyumbani",
    "login": "Ingia",
    "logout": "Toka",
    "username": "Jina la mtumiaji",
    "password": "Neno la Siri",
    "settings": "Mipango",
    "theme": "Mandhari",
    "language": "Lugha",
    "cancel": "Ghairi",
    "loading": "Inapakia…",
    "online": "Mtandaoni",
    "offline": "Nje ya Mtandao",
    "synced": "Imesawazishwa",
    "pending": "Inasubiri",

    "nav.home": "Nyumbani",
    "nav.history": "Historia",
    "nav.history.title": "Historia ya Miamala",
    "nav.scan": "Changanua",
    "nav.scan.title": "Changanua Dereva",
    "nav.analytics": "Uchambuzi",
    "nav.analytics.title": "Uchambuzi Wangu",
    "nav.profile": "Wasifu",
    "nav.profile.title": "Wasifu Wangu",

    "home.greeting.morning": "Habari za asubuhi",
    "home.greeting.afternoon": "Habari za mchana",
    "home.greeting.evening": "Habari za jioni",
    "home.sync.complete": "Usawazishaji Umekamilika",
    "home.sync.synced": "zimesawazishwa",
    "home.sync.failed": "zimeshindwa",
    "home.sync.failed.title": "Usawazishaji Umeshindwa",
    "home.syncing": "Inasawazisha…",
    "home.pending.tap": "zinasubiri — Gusa kusawazisha",
    "home.today": "Leo",
    "home.today.levy": "Zabuni ya Leo",
    "home.pending": "Inasubiri",
    "home.live.rate": "KIWANGO CHA MOJA KWA MOJA",
    "home.rate.unavailable": "Kiwango hakipatikani",
    "home.new.transaction": "Muamala Mpya",
    "home.new.transaction.sub": "Rekodi mauzo ya mafuta na zabuni ya 2%",
    "home.verify.receipt": "Thibitisha Risiti",
    "home.all.history": "Historia Yote",
    "home.this.month": "Mwezi Huu",
    "home.transactions": "Miamala",
    "home.levy.collected": "Zabuni Zilizokusanywa",
    "home.synced": "Imesawazishwa",
    "home.total.alltime": "Jumla Yote",
    "home.recent": "Hivi Karibuni",
    "home.see.all": "Ona zote",
    "home.levy.footer": "Zabuni ya maombi ya 2% inasaidia mfuko wa kibinadamu wa LCI",

    "history.levy": "zabuni",
    "history.filter.all": "Zote",
    "history.filter.synced": "Imesawazishwa",
    "history.filter.pending": "Inasubiri",
    "history.records": "rekodi",
    "history.search.placeholder": "Tafuta kanisa, mafuta, risiti…",
    "history.empty.nomatch": "Hakuna miamala inayolingana",
    "history.empty.none": "Bado hakuna miamala",
    "history.empty.nomatch.sub": "Jaribu kurekebisha utafutaji au kichujio chako",
    "history.empty.none.sub": "Mauzo yako ya kwanza yataonekana hapa",

    "scan.permission.title": "Ufikiaji wa kamera unahitajika",
    "scan.permission.subtitle": "Freddy hutumia kamera kuchanganua msimbo wa QR wa kitambulisho cha dereva na kuonyesha historia yake ya zabuni.",
    "scan.permission.grant": "Ruhusu ufikiaji",
    "scan.hint": "Elekeza kamera kwenye msimbo wa QR wa dereva",

    "analytics.today": "Leo",
    "analytics.this.month": "Mwezi Huu",
    "analytics.all.time": "Wakati Wote",
    "analytics.transactions": "Miamala",
    "analytics.levy.collected": "Zabuni Zilizokusanywa",
    "analytics.avg.per.tx": "Wastani kwa Muamala",
    "analytics.sync.status": "Hali ya Usawazishaji",
    "analytics.total": "Jumla",
    "analytics.synced.pct": "imesawazishwa",
    "analytics.top.churches": "Makanisa Bora",
    "analytics.levy.lower": "zabuni",
    "analytics.by.fuel.type": "Kwa Aina ya Mafuta",
    "analytics.levy.programme": "Mpango wa Zabuni ya Maombi",
    "analytics.levy.programme.body": "Kila muamala wa mafuta unaorekodi unachangia zabuni ya 2% kwa mfuko wa kibinadamu wa LCI. Kazi yako inasaidia moja kwa moja jamii za Lubumbashi.",
    "analytics.total.contributed": "Jumla iliyochangwa",
    "analytics.levy.rate": "Kiwango cha zabuni",

    "profile.signout": "Toka",
    "profile.signout.confirm": "Una uhakika unataka kutoka?",
    "profile.role.agent": "Wakala wa Uwanjani",
    "profile.role.manager": "Msimamizi wa Kituo",
    "profile.role.admin": "Msimamizi",
    "profile.role.auditor": "Mkaguzi",
    "profile.levy.raised": "Zabuni Zilizokusanywa",
    "profile.assignment": "Mgawo",
    "profile.quick.actions": "Vitendo vya Haraka",
    "profile.verify.receipt": "Thibitisha Risiti",
    "profile.verify.receipt.sub": "Angalia nambari yoyote ya risiti ya LCI",
    "profile.settings.sub": "Mandhari, lugha, na printa",
    "profile.pending.tx": "Ona Miamala Inayosubiri",
    "profile.pending.tx.sub": "Rekodi zinazosubiri kusawazishwa",
    "profile.about": "Kuhusu",
    "profile.app": "Programu",
    "profile.version": "Toleo",
    "profile.levy.rate": "Kiwango cha Zabuni",
    "profile.programme": "Mpango",

    "login.missing.fields": "Sehemu zinakosekana",
    "login.missing.fields.body": "Weka jina lako la mtumiaji na neno la siri.",
    "login.failed": "Kuingia kumeshindwa",
    "login.failed.body": "Taarifa si sahihi. Tafadhali jaribu tena.",
    "login.welcome": "Karibu tena",
    "login.welcome.sub": "Ingia kwenye akaunti yako ya wakala",
    "login.username.placeholder": "Weka jina lako la mtumiaji",
    "login.password.placeholder": "Weka neno lako la siri",
    "login.signin": "Ingia",
    "login.footer": "Salama · Inafanya Kazi Nje ya Mtandao · Zabuni ya Maombi 2%",

    "newtx.step.fueltype": "Aina ya Mafuta",
    "newtx.step.amount": "Kiasi",
    "newtx.step.preview": "Muonekano",
    "newtx.select.fueltype": "Chagua Aina ya Mafuta",
    "newtx.select.church": "Chagua Kanisa",
    "newtx.next": "Ifuatayo →",
    "newtx.enter.amount": "Weka Kiasi",
    "newtx.amount.in": "Kiasi kwa",
    "newtx.live.breakdown": "Uchambuzi wa Moja kwa Moja",
    "newtx.for": "Kwa",
    "newtx.driver.phone": "Simu ya dereva (hiari)",
    "newtx.driver.phone.hint": "Inaunganisha zabuni hii kwa dereva ili ionekane kwenye historia yake anapochanganuliwa.",
    "newtx.notes": "Maelezo (hiari)",
    "newtx.back": "← Rudi",
    "newtx.review": "Kagua →",
    "newtx.confirm": "Thibitisha Muamala",
    "newtx.currency": "Sarafu",
    "newtx.edit": "← Hariri",
    "newtx.submit": "Wasilisha Muamala",

    "detail.not.found": "Muamala haukupatikana",
    "detail.go.back": "Rudi Nyuma",
    "detail.synced": "Imesawazishwa kwa seva",
    "detail.pending": "Inasubiri kusawazishwa — itapakiwa ukiwa mtandaoni",
    "detail.transaction.details": "Maelezo ya Muamala",
    "detail.est": "makadirio",
    "detail.timestamp": "Muhuri wa Muda",
    "detail.date": "Tarehe",
    "detail.time": "Muda",
    "detail.back.history": "Rudi kwa Historia",

    "verify.title": "Thibitisha Risiti",
    "verify.subtitle": "Weka nambari ya risiti ya LCI kuthibitisha kuwa muamala ni halisi",
    "verify.not.found": "Risiti haikupatikana. Angalia nambari na ujaribu tena.",
    "verify.valid": "Risiti Halali",
    "verify.valid.sub": "Muamala huu ni halisi",
    "verify.amount": "Kiasi",
    "verify.status": "Hali",

    "driver.not.found": "Dereva hakupatikana.",
    "driver.unknown": "Dereva asiyejulikana",
    "driver.total.levy": "Jumla ya zabuni",
    "driver.total.fuel": "Jumla ya mafuta",
    "driver.record.purchase": "Rekodi ununuzi",
    "driver.new.purchase": "Ununuzi mpya",
    "driver.no.phone.warn": "Hakuna simu iliyorekodiwa — haitaunganishwa na historia.",
    "driver.amount.purchased": "Kiasi kilichonunuliwa",
    "driver.contribution": "Mchango (2%)",
    "driver.auto.calculated": "Imehesabiwa kiotomatiki",
    "driver.receiving.church": "Kanisa linalopokea",
    "driver.no.church": "Hakuna kanisa linalopatikana kwa kituo chako.",
    "driver.save.purchase": "Hifadhi ununuzi",
    "driver.previous.tx": "Miamala iliyopita",
    "driver.no.tx": "Hakuna miamala ya zabuni iliyorekodiwa kwa dereva huyu bado.",
    "driver.fuel": "mafuta",
    "driver.recorded": "Imerekodiwa",
    "driver.recorded.body": "Ununuzi na mchango wa 2% umehifadhiwa.",
    "driver.saved.offline": "Imehifadhiwa nje ya mtandao",
    "driver.saved.offline.body": "Hakuna muunganisho kwa sasa — itasawazishwa kiotomatiki na kuonekana kwenye historia ya dereva huyu mara itakaposawazishwa.",
    "driver.couldnt.load": "Imeshindwa kupakia dereva",
    "driver.unknown.error": "Hitilafu isiyojulikana.",
    "driver.back.scan": "Rudi kwa uchanganuzi",

    "printer.list.error": "Imeshindwa kuorodhesha vifaa vya Bluetooth.",
    "printer.set": "Printa Imewekwa",
    "printer.set.body": "itatumika kwa risiti.",
    "printer.print.failed": "Uchapishaji Umeshindwa",
    "printer.print.failed.body": "Imeshindwa kufikia printa.",
    "printer.intro": "Unganisha printa yako ya joto ya 58mm kwenye mipangilio ya Bluetooth ya Android kwanza, kisha uichague hapa chini. Risiti huchapishwa moja kwa moja kwenye printa hii.",
    "printer.active": "PRINTA HAI",
    "printer.test": "Jaribu Kuchapisha",
    "printer.forget": "Sahau",
    "printer.paired.devices": "Vifaa Vilivyounganishwa",
    "printer.no.devices": "Hakuna vifaa vya Bluetooth vilivyounganishwa vilivyopatikana. Unganisha printa yako kwenye Mipangilio ya Android, kisha gusa onyesha upya.",
    "printer.unknown.device": "Kifaa kisichojulikana",
    "printer.done": "Imekamilika",
    "printer.retry": "Jaribu Tena",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem("language").then((savedLang) => {
      if (savedLang === "en" || savedLang === "fr" || savedLang === "sw") {
        setLanguageState(savedLang);
      }
      setLoaded(true);
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  if (!loaded) return null;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
