# Generated by Django 5.1.4 on 2026-05-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_notification'),
        ('fuel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='fuel_app.fuelstation'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='fuel_app.parentcompany'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('NGO_ADMIN', 'NGO Admin'), ('COMPANY_MANAGER', 'Company Manager'), ('STATION_AGENT', 'Station Agent')], default='STATION_AGENT', max_length=20),
        ),
    ]
